#!/usr/bin/env python3
"""Generate the README convergence demo from measured Salix data."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import _path  # noqa: F401

from lib.distance import compute_gaps
from lib.stats import analyze

PROMPT = "Write a short note explaining why focused work matters."

BENCHMARK_SAMPLE = """
The implications of focused work are, perhaps, less dramatic than they first
appear. A person could argue that attention itself imposes constraints; indeed,
those constraints shape the quality of the result. Rather than rush from one
prompt to the next, the work unfolds slowly, turning each problem over before
committing it to the page. There is, however, a practical advantage: the
important issue becomes specific. Once it is specific, the answer usually
becomes smaller, clearer, and less wasteful.
"""

DRAFT_ITERATIONS = [
    {
        "label": "full_ai_baseline",
        "text": (
            "Focused work matters because it gives people time to think. "
            "Noise makes priorities unclear. A focused block helps people "
            "solve the real problem. It also helps them finish with less waste."
        ),
    },
    {
        "label": "recursive_edit_1",
        "text": (
            "Focused work matters because it gives people time, perhaps, to think. "
            "Noise makes priorities unclear. A focused block helps people solve "
            "the real problem, and it also helps them finish with less waste."
        ),
    },
    {
        "label": "recursive_edit_2",
        "text": (
            "Focused work matters because it gives people time, perhaps, to think "
            "before the day breaks into fragments. Noise makes priorities unclear; "
            "indeed, a focused block helps people solve the real problem, and it "
            "helps them finish with less waste."
        ),
    },
    {
        "label": "recursive_edit_3",
        "text": (
            "Focused work matters because it gives people time, perhaps, to think "
            "before the day breaks into fragments. Rather than chase every "
            "interruption, the work sits still long enough to become specific. "
            "Indeed, once the real problem is visible, the answer becomes smaller, "
            "clearer, and less wasteful."
        ),
    },
]

TRACKED_CHARTS = [
    {
        "feature": "punct_comma_per1k",
        "title": "Comma cadence convergence",
        "unit": "commas per 1,000 words",
    },
    {
        "feature": "mean_sent_len",
        "title": "Sentence length convergence",
        "unit": "words per sentence",
    },
]


def build_payload() -> dict:
    benchmark_stats = analyze((BENCHMARK_SAMPLE + "\n") * 4)
    iterations = []
    for index, item in enumerate(DRAFT_ITERATIONS):
        stats = analyze(item["text"])
        gap = compute_gaps(stats, benchmark_stats)
        row = {
            "iteration": index,
            "label": item["label"],
            "total_distance": gap["total_distance"],
            "top_gap": gap["top_gaps"][0]["feature"] if gap["top_gaps"] else "",
        }
        for chart in TRACKED_CHARTS:
            feature = chart["feature"]
            row[feature] = stats[feature]
            row[f"benchmark_{feature}"] = benchmark_stats[feature]
        iterations.append(row)

    charts = []
    for chart in TRACKED_CHARTS:
        feature = chart["feature"]
        charts.append({
            **chart,
            "target_series": [
                {"iteration": row["iteration"], "value": row[feature]} for row in iterations
            ],
            "benchmark_series": [
                {"iteration": row["iteration"], "value": row[f"benchmark_{feature}"]}
                for row in iterations
            ],
        })

    payload = {
        "prompt": PROMPT,
        "source": "Generated by scripts/demo_convergence.py from fixed benchmark and draft fixtures.",
        "validated": False,
        "iterations": iterations,
        "charts": charts,
    }
    validate_payload(payload)
    payload["validated"] = True
    return payload


def validate_payload(payload: dict) -> None:
    distances = [row["total_distance"] for row in payload["iterations"]]
    for previous, current in zip(distances, distances[1:]):
        if not current < previous:
            raise SystemExit(
                f"Demo distance must strictly decrease; saw {previous} then {current}."
            )
    for chart in payload["charts"]:
        target = chart["target_series"]
        benchmark = chart["benchmark_series"]
        initial_gap = abs(target[0]["value"] - benchmark[0]["value"])
        final_gap = abs(target[-1]["value"] - benchmark[-1]["value"])
        if not final_gap < initial_gap:
            raise SystemExit(
                f"{chart['feature']} must converge; gap {initial_gap} -> {final_gap}."
            )


def _points(series: list[dict], *, x: float, y: float, width: float, height: float,
            min_value: float, max_value: float) -> str:
    span = max(max_value - min_value, 0.001)
    x_step = width / max(len(series) - 1, 1)
    out = []
    for index, point in enumerate(series):
        px = x + index * x_step
        py = y + height - ((point["value"] - min_value) / span * height)
        out.append(f"{px:.1f},{py:.1f}")
    return " ".join(out)


def render_svg(payload: dict) -> str:
    width = 920
    panel_height = 250
    margin = 64
    chart_width = width - margin * 2
    height = 110 + panel_height * len(payload["charts"])
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}" role="img" '
        'aria-labelledby="title desc">',
        "<title id=\"title\">Validated real Salix fixture convergence</title>",
        "<desc id=\"desc\">Two measured chart lines show recursive drafts converging toward a benchmark style profile.</desc>",
        "<rect width=\"100%\" height=\"100%\" fill=\"#fbfaf7\"/>",
        '<text x="40" y="38" font-family="Arial, sans-serif" font-size="22" '
        'font-weight="700" fill="#1f2933">Validated real Salix fixture</text>',
        '<text x="40" y="64" font-family="Arial, sans-serif" font-size="13" '
        'fill="#52616b">Generated from scripts/demo_convergence.py; tested for decreasing total distance and feature convergence.</text>',
    ]
    for chart_index, chart in enumerate(payload["charts"]):
        top = 94 + chart_index * panel_height
        plot_x = margin
        plot_y = top + 42
        plot_h = 138
        values = [point["value"] for point in chart["target_series"] + chart["benchmark_series"]]
        pad = max((max(values) - min(values)) * 0.12, 1.0)
        min_value = min(values) - pad
        max_value = max(values) + pad
        target_points = _points(
            chart["target_series"], x=plot_x, y=plot_y, width=chart_width,
            height=plot_h, min_value=min_value, max_value=max_value,
        )
        benchmark_points = _points(
            chart["benchmark_series"], x=plot_x, y=plot_y, width=chart_width,
            height=plot_h, min_value=min_value, max_value=max_value,
        )
        parts.extend([
            f'<text x="{margin}" y="{top + 12}" font-family="Arial, sans-serif" '
            f'font-size="17" font-weight="700" fill="#1f2933">{chart["title"]}</text>',
            f'<text x="{margin}" y="{top + 32}" font-family="Arial, sans-serif" '
            f'font-size="12" fill="#52616b">{chart["unit"]}</text>',
            f'<line x1="{plot_x}" y1="{plot_y + plot_h}" x2="{plot_x + chart_width}" '
            f'y2="{plot_y + plot_h}" stroke="#c9d1d9" stroke-width="1"/>',
            f'<line x1="{plot_x}" y1="{plot_y}" x2="{plot_x}" y2="{plot_y + plot_h}" '
            f'stroke="#c9d1d9" stroke-width="1"/>',
            f'<polyline points="{benchmark_points}" fill="none" stroke="#b45309" '
            f'stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>',
            f'<polyline points="{target_points}" fill="none" stroke="#2563eb" '
            f'stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>',
            f'<text x="{margin}" y="{plot_y + plot_h + 34}" '
            f'font-family="Arial, sans-serif" font-size="12" fill="#2563eb">Draft line</text>',
            f'<text x="{margin + 96}" y="{plot_y + plot_h + 34}" '
            f'font-family="Arial, sans-serif" font-size="12" fill="#b45309">Benchmark line</text>',
        ])
        for point_index, row in enumerate(payload["iterations"]):
            px = plot_x + point_index * (chart_width / max(len(payload["iterations"]) - 1, 1))
            parts.append(
                f'<text x="{px:.1f}" y="{plot_y + plot_h + 18}" '
                'font-family="Arial, sans-serif" font-size="11" text-anchor="middle" '
                f'fill="#52616b">{row["iteration"]}</text>'
            )
    parts.append("</svg>")
    return "\n".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate validated Salix convergence demo data.")
    parser.add_argument("--json-out", default="examples/convergence_demo.json")
    parser.add_argument("--svg-out", default="examples/convergence_demo.svg")
    args = parser.parse_args()

    payload = build_payload()
    json_path = Path(args.json_out)
    svg_path = Path(args.svg_out)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    svg_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(payload, indent=2) + "\n")
    svg_path.write_text(render_svg(payload) + "\n")
    print(f"Wrote {json_path}")
    print(f"Wrote {svg_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
